In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df_duration = pd.read_csv("../data/duration.csv")
df_e_price = pd.read_csv("../data/e_price.csv")
df_occupancy = pd.read_csv("../data/occupancy.csv")
df_s_price = pd.read_csv("../data/s_price.csv")
df_volume = pd.read_csv("../data/volume.csv")

In [3]:
df_occupancy.head()

,time,1001,1002,1003,1004,1005,1006,1007,1008,1009,...,2673,2674,2675,2676,2677,2678,2679,2680,2681,2682
0,2022-09-01 00:00:00,4.0,9.0,2.0,10.0,5.0,4.0,0.0,20.0,36.0,...,16.0,1.0,4.0,5.0,6.0,0.0,4.0,2.0,2.0,0.0
1,2022-09-01 01:00:00,7.0,6.0,2.0,6.0,5.0,7.0,0.0,19.0,47.0,...,25.0,2.0,10.0,6.0,7.0,0.0,3.0,3.0,3.0,0.0
2,2022-09-01 02:00:00,7.0,3.0,1.0,10.0,5.0,8.0,0.0,20.0,60.0,...,17.0,1.0,0.0,5.0,8.0,0.0,7.0,3.0,1.0,0.0
3,2022-09-01 03:00:00,8.0,3.0,1.0,10.0,5.0,8.0,0.0,20.0,58.0,...,17.0,1.0,10.0,5.0,8.0,0.0,7.0,3.0,1.0,0.0
4,2022-09-01 04:00:00,6.0,6.0,2.0,8.0,5.0,7.0,0.0,19.0,54.0,...,25.0,2.0,10.0,5.0,7.0,0.0,3.0,3.0,2.0,0.0

In [4]:
df_e_price.head()

,time,1001,1002,1003,1004,1005,1006,1007,1008,1009,...,2673,2674,2675,2676,2677,2678,2679,2680,2681,2682
0,2022-09-01 00:00:00,1.2,1.0,1.1,0.32,0.79,0.2962,0.7402,1.0,0.3067,...,0.7,0.34,0.35,0.72,0.72,0.0,0.72,0.72,1.0,1.05
1,2022-09-01 01:00:00,1.2,1.0,1.1,0.32,0.79,0.2962,0.7402,1.0,0.3067,...,0.7,0.34,0.35,0.72,0.72,0.0,0.72,0.72,1.0,1.05
2,2022-09-01 02:00:00,1.2,1.0,1.1,0.32,0.79,0.2962,0.7402,1.0,0.3067,...,0.7,0.34,0.35,0.72,0.72,0.0,0.72,0.72,1.0,1.05
3,2022-09-01 03:00:00,1.2,1.0,1.1,0.32,0.79,0.2962,0.7402,1.0,0.3067,...,0.7,0.34,0.35,0.72,0.72,0.0,0.72,0.72,1.0,1.05
4,2022-09-01 04:00:00,1.2,1.0,1.1,0.32,0.79,0.2962,0.7402,1.0,0.3067,...,0.7,0.34,0.35,0.72,0.72,0.0,0.72,0.72,1.0,1.05

In [5]:
df_s_price.head()

,time,1001,1002,1003,1004,1005,1006,1007,1008,1009,...,2673,2674,2675,2676,2677,2678,2679,2680,2681,2682
0,2022-09-01 00:00:00,0.47,0.66,0.76,0.76,0.29,1.1438,1.1498,0.66,0.8733,...,0.76,0.82,0.73,0.76,0.76,0.52,0.76,0.76,0.52,0.7
1,2022-09-01 01:00:00,0.47,0.66,0.76,0.76,0.29,1.1438,1.1498,0.66,0.8733,...,0.76,0.82,0.73,0.76,0.76,0.52,0.76,0.76,0.52,0.7
2,2022-09-01 02:00:00,0.47,0.66,0.76,0.76,0.29,1.1438,1.1498,0.66,0.8733,...,0.76,0.82,0.73,0.76,0.76,0.52,0.76,0.76,0.52,0.7
3,2022-09-01 03:00:00,0.47,0.66,0.76,0.76,0.29,1.1438,1.1498,0.66,0.8733,...,0.76,0.82,0.73,0.76,0.76,0.52,0.76,0.76,0.52,0.7
4,2022-09-01 04:00:00,0.47,0.66,0.76,0.76,0.29,1.1438,1.1498,0.66,0.8733,...,0.76,0.82,0.73,0.76,0.76,0.52,0.76,0.76,0.52,0.7